### ISSUE TITLE
CollaboratorsCtrl does not remove COLLABORATOR_* event listener

### ISSUE THREAD

**Issue by soundTricker** [googlearchive/realtime-tasks#1]
Hi.

Right now, I'm trying migrate from this app to coffeescript for learning.

so I found some bugs.

At [app.js#138](https://github.com/googledrive/realtime-tasks/blob/master/app/scripts/controllers/todos.js#L138).

``` javascript
$scope.$on('$destroy', function () {
    var doc = $scope.document;
    if (doc) {
      document.removeEventListener(gapi.drive.realtime.EventType.COLLABORATOR_LEFT, collaboratorListener);
      document.removeEventListener(gapi.drive.realtime.EventType.COLLABORATOR_JOINED, collaboratorListener);
    }
});
```

but it seems removing window.document event listener.
I guess, it should be...

``` javascript
$scope.$on('$destroy', function () {
    var doc = $scope.document;
    if (doc) {
      doc.removeEventListener(gapi.drive.realtime.EventType.COLLABORATOR_LEFT, collaboratorListener);
      doc.removeEventListener(gapi.drive.realtime.EventType.COLLABORATOR_JOINED, collaboratorListener);
    }
});
```

So the collaboratorListener is executed several times on fire $destory event.

**Note**
It can not found on view.
maybe it can found only by debuging.

And sorry.
right now , I can't send pull request...

**Comment by sqrrrl** [comment]
Thanks, just fixed & will update live version soon

**Comment by soundTricker** [comment]
Thanks for quick reply @sqrrrl :)

I think this app is so cool.
awesome!!!
